---

- hosts: linux 
  become: yes
  roles:
    - ansible-role-version-gather-linux

- hosts: localhost
  become: yes
  become_user: davemus
  post_tasks:
    - name: running ansible facts
      shell: ansible linux -m setup | grep local_fact
      register: result
    - debug: msg="{{ result.stdout.split('\n') }}"     

